<?php

declare (strict_types=1);
use SanderMuller\BoostCore\Config\BoostConfig;
use SanderMuller\BoostCore\Enums\Agent;
/**
 * boost-core configuration.
 *
 * Generated by `composer boost:install`. Re-run that command to update
 * agents/vendors interactively, or hand-edit this file. After changes
 * run `composer boost:sync`.
 *
 * Docs: https://github.com/sandermuller/boost-core
 */
return BoostConfig::configure()->withAgents([\SanderMuller\BoostCore\Enums\Agent::CLAUDE_CODE, \SanderMuller\BoostCore\Enums\Agent::COPILOT, \SanderMuller\BoostCore\Enums\Agent::CODEX])->withAllowedVendors(['sandermuller/repo-init', 'sandermuller/package-boost-php', 'stolt/lean-package-validator'])->withDisabledEmitters([]);